### ISSUE TITLE
SP flash tool version

### ISSUE THREAD

**Issue by shomykohai** [progzone122/penangf-sp-flash-tool#1]
Hello,
been following the work of you all for a while

I looked through this sp flash tool and it 1:1 matches with this other one
https://spflashtools.com/windows/sp-flash-tool-v5-2216

Some file surely differ, but not the code itself.

I've also looked through the source code of another version:
https://github.com/acontini/SP-Flash-Tool-src

This hopefully means moto didn't add some weird stuff that only their sp flash tool has to make the phone stay in brom. 

There are some interesting files under the `Conn` directory.
Stuff related to Brom!

If y'all managed to compile a custom sp flash tool you may be able to make the phone stay in brom by stopping the execution right after it enter brom 🤔 Or even make it unlock the bootloader somehow

In the sp flash tool i attached there are also some other DA files, didn't test em tho.

**Comment by progzone122** [comment]
Hello! Thanks for the info!
We definitely won't be able to access BROM directly (most likely due to chipset limitations).
We can access Preloader, load DA file through it and only then we can somehow interact with BROM (but very limited, because DA file is very castrated, Motorola cut out almost all functions from there!).
We can hold it in "USB VCOM DA" using mtkclient, you only need to specify preloader & loader
![IMG_20241120_224444_637.jpg](https://github.com/user-attachments/assets/0b41c85c-a984-4516-b1e7-8a4111370b42)
But the result is still the same - UNSUPPORTED OP. Most likely we need to edit the DA file.

If you are interested or want to help, join our group in telegram - https://t.me/motoheliog85

**Comment by progzone122** [comment]
After testing it was also found out that ANY flash tool works with penangf, you just need to specify the correct DA file and turn off the "Check LIB DA match" function in the settings

**Comment by progzone122** [comment]
Detailed information about this is in the telegram chat

**Comment by shomykohai** [comment]
Mmh I see.

I remember trying the same stuff a long ago, specifying da and reloader with mtkclient and getting no results.

Tho, I remember finding another DA file online for MT6768 that gave me the same results as the official one (DA_NO_PL_V6), and in fact got the DA_HASH_MISMATCH error.

You could also try using one of the da files included in the sp flash tool I linked above to check for compatibility 🤔


I wonder what sp flash tool does different than mtkclient to connect to brom by preloader.

Unfortunately I can't join the channel, though I might be able to view it.

**Comment by progzone122** [comment]
> Mmh I see.
> 
> I remember trying the same stuff a long ago, specifying da and reloader with mtkclient and getting no results.

There is a video instruction in the telegram group on what exactly to do so that mtkclient recognizes the device

**Comment by progzone122** [comment]
> I wonder what sp flash tool does different than mtkclient to connect to brom by preloader.

mtkclient can also connect via da functionality to brom

**Comment by progzone122** [comment]
Updated the Releases tab, finally found DA, which showed that it was possible to successfully connect to mtkclient!

**Comment by shomykohai** [comment]
> Updated the Releases tab, finally found DA, which showed that it was possible to successfully connect to mtkclient!

Good to know!!

Does this DA allow to write on protected partitions? Cause I read somewhere that somehow some DA have protection for some partitions (like seccfg which is the one we are all interested in).

Have you tried with MTK_AllInOne?
In my past attempts I tried but unfortunately didn't work, but could just be me not finding the correct DA 🤔.

Anyway thanks for the new DA!

**Comment by shomykohai** [comment]
Looks like the new DA file still doesn't allow for writing partitions, but at least we can make backups!

I have found this DA file online, but can't test it right now:
https://androiddatahost.com/kjhbt

It weights way more than MT6768_USER.bin, so it *might* work (or at least I hope so) 

@progzone122

**Comment by progzone122** [comment]
> Looks like the new DA file still doesn't allow for writing partitions, but at least we can make backups!
> 
> I have found this DA file online, but can't test it right now: https://androiddatahost.com/kjhbt
> 
> It weights way more than MT6768_USER.bin, so it _might_ work (or at least I hope so)
> 
> @progzone122

Not only do backups but also modify vbmeta exactly but I still get red state and record sections (but not all)
https://github.com/progzone122/fuckyoumoto

**Comment by progzone122** [comment]
> I have found this DA file online, but can't test it right now:
> https://androiddatahost.com/kjhbt

upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)

**Comment by shomykohai** [comment]
> Not only do backups but also modify vbmeta exactly but I still get red state and record sections (but not all)
> https://github.com/progzone122/fuckyoumoto

Could the redstate be related to this? (from xda discord server, mtk megathread)

![Screenshot_20241122_111618_Discord.png](https://github.com/user-attachments/assets/2fe3e2fc-4e66-45aa-9c7b-ac24496d6abc)

moto g13 and g23 have that exact cpu
